### ISSUE TITLE
KB API test suite sometimes seems to hang

### ISSUE THREAD

**Issue by nwinant** [cycorp/CycCoreAPI#1]
Running an install (with tests) of the CycCoreAPI project, it'll get to a point on the KB API tests with something like this:
```
 T E S T S
-------------------------------------------------------
Running com.cyc.kb.quant.ForAllQuantifiedInstanceLiteralTest
Mar 1, 2015 5:53:16 PM com.cyc.kb.client.KBAPITestConstants getInstance
INFO: Instantiating KBAPITestConstants..
```
And then it will just hang, seemingly forever. To be fair, I don't think I've let it go for more than 5-10 minutes before killing it, but it's clearly a bug.

However, it only happens sometimes. Subsequent runs of the tests will go just fine.

**Comment by cyc-dev** [comment]
This should be resolved by [commit d087ff4a6a7f2474f9f208e943076e0d3ef76f79](https://github.com/cycorp/CycCoreAPI/commit/d087ff4a6a7f2474f9f208e943076e0d3ef76f79).

**Comment by nwinant** [comment]
This issue was moved to cycorp/new-ish#1

**Comment by cyc-dev** [comment]
This issue was moved to cycorp/cyc-issues#3

**Comment by cyc-dev** [comment]
This issue was moved to cycorp/cyc-issues#1
