### ISSUE TITLE
Missing formulatemplate.dtd

### ISSUE THREAD

**Issue by nwinant** [cycorp/CycCoreAPI#4]
The formula template code (specifically, formula-templates.lisp) requires a DTD at http://dev.cyc.com/dtd/formulatemplate.dtd, but said DTD was apparently not copied over during the Cyc Dev Center migration to GitHub.

This issue is not apparent when building the APIs, but causes an exception when running `com.cyc.km.query.construction.ConstructingQueries` in the CoreAPIUseCases.

Reported via [Disqus comment #1975361352](http://dev.cyc.com/index.html#comment-1975361352) on 2015-04-19.

**Comment by nwinant** [comment]
I've created the [cyc-dtds](https://github.com/cycorp/cyc-dtds) git repo which contains the relevant DTDs, and have published them to dev.cyc.com.

**Comment by cyc-dev** [comment]
This issue was moved to cycorp/cyc-issues#4
